# Generated by Django 6.0 on 2025-12-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='especialidad',
        ),
    ]