# Generated by Django 6.0 on 2025-12-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0002_remove_especialidad_from_turno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
    ]
